version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: simplebank_db
    environment:
      POSTGRES_USER: asani
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: simplebank_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asani -d simplebank_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simplebank_backend
    environment:
      PORT: "8080"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: asani
      DB_PASSWORD: secretpassword
      DB_NAME: simplebank_db
      APP_ENV: development
      JWT_SECRET: simplebank_super_secret_jwt_key_2026_dev_mode
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: simplebank_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  pgdata:
